use_frameworks!

pod 'Mixpanel', '~> 2.8'
pod 'SVProgressHUD', '~> 1.1'
pod 'SHSPhoneComponent', '~> 2.15'
pod 'libPhoneNumber-iOS', '~> 0.8'
pod 'LLSimpleCamera', '~> 4.0'
pod 'MoABContactsManager', '~> 1.0'
pod 'CWStatusBarNotification', '~> 2.3'
pod 'NYTPhotoViewer', '~> 0.1'
pod 'FLAnimatedImage', '~> 1.0'
pod 'Parse', '~> 1.11'
pod 'ParseCrashReporting', '~> 1.9'
pod 'CSStickyHeaderFlowLayout', '~> 0.2'
pod 'JSQWebViewController', '~> 2.0'
pod 'FormatterKit', '~> 1.8'
pod 'KTBTaskQueue', '~> 1.0'
pod 'JMImageCache', '~> 0.4'
pod 'Fabric'
pod 'Crashlytics'
pod 'TTTAttributedLabel', '~> 1.13'
pod 'TagListView', '~> 0.4'